### ISSUE TITLE
Make Group Assignments more resilient  

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom#1452]
## Why Group Assignments?
Group assignments account for roughly ~15% of all assignments and as such should be as resilient as individual assignments. Individual assignments have recently been made much more resilient (see https://github.com/education/classroom/projects/9).

## Requirements to make Group Assignments resilient
- [x] Track progress of repo setup with a 1:N:1 model of `Group`:`GroupInviteStatus`:`GroupInvitation` #1456
- [x] `#show`, `#setupv2`, `#create_repo`, and `#success` routes. (Possibly a `#progress` route) 
https://github.com/education/classroom/issues/1487
- [x] route based on invite status #1490 
- [x] make the invitation redemption change the `invite_status` #1499 
- [x] ActionCable channel for group assignments progress #1501 
- [x] Creation job similar to `CreateGitHubRepositoryJob`#1519
- [x] Implement #create_repo #1520 
- [x] Front end like `setupv2`
- [x] Import status job similar to `PorterStatusJob`

**Comment by d12** [comment]
@BenEmdon This system may need to work slightly differently than the normal assignments. 

a) Groups are shared between multiple assignments. Does it make sense to have statuses attached to groups?
b) There are two different steps to processing an invitation redemption for a group assignment. If the user is the first in the group to redeem, we create the repository. Then we add them as a collaborator. If the user isn't the first, we only add them as a collaborator. The statuses should support both flows.

Would you be able to map out how the process works currently with all the different classes and relationships, and how it will work after this project is finished? I'd love to have everything planned out before we go ahead with migrations.

**Comment by BenEmdon** [comment]
> a) Groups are shared between multiple assignments. Does it make sense to have statuses attached to groups?

`GroupInviteStatus` are attached a `GroupAssignmentInvitation` and a `Group`. This way a `GroupInviteStatus` is unique to assignment/group.

> b) There are two different steps to processing an invitation redemption for a group assignment. If the user is the first in the group to redeem, we create the repository. Then we add them as a collaborator. If the user isn't the first, we only add them as a collaborator. The statuses should support both flows.
  
>  Would you be able to map out how the process works currently with all the different classes and relationships, and how it will work after this project is finished? I'd love to have everything planned out before we go ahead with migrations.

Will do, sounds like a plan. Will take some time to investigate.

**Comment by BenEmdon** [comment]
Looks like there is no need to add users as a collaborator for group assignments. 
Since each group is really just a GitHub team, all we need to do is add them to the GitHub team. 
Teams on GitHub have repo access:
<img width="997" alt="screen shot 2018-08-03 at 3 43 05 pm" src="https://user-images.githubusercontent.com/11095731/43668876-30b2e48c-9734-11e8-8d2d-7ae78b04aba9.png">

**Comment by BenEmdon** [comment]
## Here is the current action flow (with before actions)
> ![frame 2](https://user-images.githubusercontent.com/11095731/43669652-66665f32-9739-11e8-881a-ec2b31e158e6.png)

## Here is the flow that would be favorable
> ![frame 3](https://user-images.githubusercontent.com/11095731/43669687-bdc4c8a4-9739-11e8-8886-9353d5033c5e.png)

**Comment by BenEmdon** [comment]
## Models 
This is what the models should look like after #1454 
![frame 4](https://user-images.githubusercontent.com/11095731/43670653-1dab7ffc-9743-11e8-998e-526fcc3d36ef.png)

_blue represents new additions_

**Comment by d12** [comment]
We chatted about this in our 1-1, but looking at this again, it all makes sense to me :+1:

**Comment by BenEmdon** [comment]
The feature is now complete and is hidden behind a beta flag.
