### ISSUE TITLE
GraphQL - Implementation Checklist

### ISSUE THREAD

**Issue by d12** [education/classroom#1518]
This is a rough list of steps that need to happen as we work towards [GraphQL in Classroom](https://github.com/education/classroom/issues/1496). This work isn't a priority, it'll mostly be happening over my weekends and evenings.

## Steps

1. Store GitHub Global Relay IDs in Classroom
  - [x] Migrations to add appropriate `github_global_relay_id` columns
  - [x] When creating Users, Organizations, or Assignment Repos, record the Global Relay ID.
  - [x] Backfill Global Relay IDs for old Users, Organizations and Assignment Repos.

2. Local GraphQL MVP
  - [x] Add required gems
  - [x] Add autogenerated graphql-ruby boilerplate
  - [x] Define local query object with a test field
  - [x] Setup local GraphQL Client
  - [x] Add rake task to allow local GraphQL testing
  - [ ] Expose a /graphql route in development only to allow developers to use cURL/graphiql for debugging
  - [x] Add a single test for the local query object test field

3. Schema Stitching API
  - [x] Setup GitHub GraphQL Client
  - [x] Setup the remote loader from [graphql-remote_loader](https://github.com/d12/graphql-remote_loader)
  - [x] Add `#global_relay_id` method to our models (this is the ID representing our local models, not GitHub models.)
  - [x] Add some field an object in our API that fetches data from the GitHub API
  - [x] Test behavior of loaded field in GraphQL via VCR (`classroom_teacher` and `classroom_org` will need GitHub Global Relay IDs, may need to go in the .env, or we can make a REST request to record it.)

4. Building out our API
  - [ ] Model our data and relationships with a GraphQL schema.
  - [ ] Develop conventions around nullability, naming, etc.
  - [ ] Develop a consistent way to test authorization, fields, connections, etc.
  - [ ] Handle upstream errors in whatever way is most appropriate.

5. Enhancing our API
  - [ ] Assert we aren't hitting the REST API when resolving a GraphQL query
  - [ ] Collect robust timing metrics. Ideally with the specificity to identify slow resolvers.
  - [ ] Lint against GraphQL anti-patterns

6. Powering views with GraphQL
  - [ ] Create a second version of views that are backed w/ GraphQL instead of REST.
  - [ ] Put second version of these views behind a feature flag
  - [ ] More tests!
  - [ ] Ensure metrics comparing old vs new version of views are available
  - [ ] Once one view is completely backed with GraphQL (ideally assignment/show or group_assignment/show), slowly enable feature flag for users
  - [ ] If metrics show a significant improvement, move forward with backing other views

7. Cleanup
  - [ ] Remove old controller logic that makes REST calls
  - [ ] Remove old views that depend on old controller logic
  - [ ] Remove `github_*.rb` namespace
  - [ ] (If there are 0 remaining REST dependencies) Remove `octokit.rb` gem.
  - [ ] Remove metrics tracking performance of old views
  - [ ] Remove feature flag

8. Exposing an integrator API (stretch goal)
  - [ ] Review all schema and make changes needed to achieve consistency
  - [ ] Ensure no resolvers are exceptionally slow
  - [ ] Develop a protocol for breaking changes
  - [ ] Prepare communications/announcements
  - [ ] Ensure developers have a channel for requesting additions to the API (likely GitHub issues)
  - [ ] Put together a sample application that uses the Classroom GraphQL API
  - [ ] Launch

cc @BenEmdon @srinjoym

**Comment by titaniumbones** [comment]
I see this has gone stale, is it still a target?

**Comment by d12** [comment]
This is not a priority right now! Are you looking for API access to Classroom data?

**Comment by titaniumbones** [comment]
Yes. ATM I can't use the Canvas integration at my school, so I rely on my own API client to interact with Canvas; I'd really like to have access to student Github id's so I can match them.

**Comment by titaniumbones** [comment]
Is this closed as won't do or b/c it's implemented?

**Comment by d12** [comment]
Closing as we're not moving forward with a GraphQL API for classroom, for internal or external use. If we expose Classroom data via an API, it'll likely be REST. #1679 is the tracking issue for this :)
