### ISSUE TITLE
Remove the `webhook_id` and `is_webhook_active` column from the Organization model

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom#1847]
### Feature request :sparkles:
Now that we have moved to using the `OrganizationWebhook` model as a source of truth for the webhook ID, we should remove the unused webhook_id column from `Organization`.

This should clean up some tech debt (and duplication).

## TODO

- [ ] Remove all usage of `Organization`'s `webhook_id`( #1850, #1848)
- [ ] Remove all usage of `Organization`'s `is_webhook_enabled`  (#1848)
- [ ] Create and run a migration to remove the columns (#1853)
