### ISSUE TITLE
Google Classroom Integration To-Do

### ISSUE THREAD

**Issue by stephaniegiang** [education/classroom#1943]
Creating an issue for me to track for the Google Classroom Integration. 

## TO-DO
- [x] Have this feature behind a feature flag `google_classroom_roster_import`
- [x] Migration merged
- [x] Get initial PR for google classroom merged https://github.com/education/classroom/pull/1791
- [x] Fix bug for sync modal https://github.com/education/classroom/pull/1991
- [x] Fix bug of not being manually able to add to roster after unlinking google classroom 
- [x] Move Google Classroom into a client
- [x] Update the README with the new .env variables https://github.com/education/classroom/pull/2014
<s>- [ ] Fix spacing on modal</s> Modal will no longer show up. 
- [ ] Allow teachers to import different identifiers other than just student name  **BLOCKED**
- [x] Fix for duplicate identifiers https://github.com/education/classroom/issues/1942 (PRs are opened!)
- [ ] Assignment creation from GitHub Classroom creates one in Google Classroom
- [ ] Submit status when student submits assignment
- [ ] Create classroom from Google Classroom

**Comment by stephaniegiang** [comment]
Just an update on Google Classroom. V1 for roster import is done. Further functionality of Google Classroom will be worked on in the near future.
