### ISSUE TITLE
Move configuration of Google Classroom to a higher level 

### ISSUE THREAD

**Issue by stephaniegiang** [education/classroom#2027]
## TO-DO

- [x] Move the authorization of Google Classroom into the application controller
- [x] When creating a new classroom, ask for the user for the integration at the beginning
- [x] With existing classroom, add a button to `Classroom profile` tab/page so that they can connect Google Classroom

## CONTEXT
After speaking with @brandonrosage, we ironed out some details on where the configuration of Google Classroom should live.

Currently Google Classroom only interacts with the roster, but in the future we would like to expand on the functionality of what the integration can do.

So to set us up for that, we decided that we should move the interaction to the classroom level. 

When creating a new classroom, we should ask the user to choose their integration. This way we can fill in the same of the classroom to match the one on their Google Classroom. It will be on this page (presented below) and above the text field. 

![image](https://user-images.githubusercontent.com/22784140/61408446-e1e4b880-a894-11e9-93dd-4e6a5c5bde9e.png)

With an existing classroom, we would present it on this page. 

![image](https://user-images.githubusercontent.com/22784140/61408322-a21dd100-a894-11e9-936b-ff815b5ee4b6.png)

**Comment by thebradbain** [comment]
And it appears #2023 will be partly taken care of by this, too! 🥳

**Comment by stephaniegiang** [comment]
This is done in https://github.com/education/classroom/pull/2038
