### ISSUE TITLE
[Tracking] Assignment invitation improvements

### ISSUE THREAD

**Issue by femmebot** [education/classroom#2275]
### Assignment invitation feature enhancements

- [ ] Enable students to quickly find their identifier from a very long list on the assignment invitation acceptance page (see:  https://github.com/education/classroom/pull/2266#issuecomment-523253355) 
- [ ] After selecting an identifier from the list, provide a way for student to confirm that they selected the correct identifier from the list and re-select the correct one if needed.
- [ ] On the student-facing assignment invitation pages, rewrite the copy from the student's point of view. Avoid the use of internal product jargon like "roster" or "identifier".
