### ISSUE TITLE
[Tracking] IA redesign

### ISSUE THREAD

**Issue by femmebot** [education/classroom#2494]
- [ ] New header / navigation
- [ ] Update Admins/TAs content layout
- [ ] Update Settings content layout 
- [ ] Update Assignment creation and Assignment view pages
- [ ] Update Roster management which includes:
  - Improved ability to search/sort roster entries
  - Updating roster management via modal
  - Layout/UI updates
- [ ] Student page view (new page with new functionality)
