### ISSUE TITLE
Internationalization roadmap

### ISSUE THREAD

**Issue by fabriciojr** [education/classroom#662]
As discussed in #308, this issue provides a roadmap to the project internationalization at all. Before add any new language inside classroom, the strings will be fully replaced by I18n keys. Each of the following changes needs to generate one pull request, this atomicity will make easier the code review, testing, tracking and collaboration on it. 
### Milestone 1: String to key replacing at views

In this milestone, we'll replace the strings on all classroom views, including the staff tools area.
- [x] Replace strings to keys at **shared** views (#732)
- [x] Replace strings to keys at **pages** view (#737)
- [ ] Replace strings to keys at **organizations** views
- [ ] Replace strings to keys at **autocomplete** views
- [ ] Replace strings to keys at **assignments** views
- [ ] Replace strings to keys at **assignments_invitations** views
- [ ] Replace strings to keys at **assignments_repos** views
- [ ] Replace strings to keys at **groups** view
- [ ] Replace strings to keys at **group_ assignments** views
- [ ] Replace strings to keys at **group_ assignments_invitations** views
- [ ] Replace strings to keys at **group_ assignments_repos** views
- [ ] Replace strings to keys at **stafftools/repo_accesses** views
- [ ] Replace strings to keys at **stafftools/organizations** views
- [ ] Replace strings to keys at **stafftools/autocomplete** views
- [ ] Replace strings to keys at **stafftools/assignments** views
- [ ] Replace strings to keys at **stafftools/assignments_invitations** views
- [ ] Replace strings to keys at **stafftools/assignments_repos** views
- [ ] Replace strings to keys at **stafftools/groupings** view
- [ ] Replace strings to keys at **stafftools/resources** view
- [ ] Replace strings to keys at **stafftools/groups** view
- [ ] Replace strings to keys at **stafftools/group_ assignments** views
- [ ] Replace strings to keys at **stafftools/group_ assignments_invitations** views
- [ ] Replace strings to keys at **stafftools/group_ assignments_repos** views
### Milestone 2:  String to key replacing at controllers

In this milestone, we'll replace the strings that are located on controllers flash messages.
- [ ] Replace strings to keys at **StarterCode** concern
- [ ] Replace strings to keys at **ApplicationController**
- [ ] Replace strings to keys at **AssignmentInvitationsController**
- [ ] Replace strings to keys at **AssignmentsController**
- [ ] Replace strings to keys at **GroupAssignmentInvitationsController**
- [ ] Replace strings to keys at **GroupAssignmentsController**
- [ ] Replace strings to keys at **OrganizationsController**

**Comment by fabriciojr** [comment]
@tarebyte I made a draft about the internationalization roadmap. I'm still concerned of any text generated by a external library that could be prompted at the screen. Could you take a look on it?

**Comment by tarebyte** [comment]
> I'm still concerned of any text generated by a external library that could be prompted at the screen. Could you take a look on it?

@fabriciojr I think the best course of action here would be to crowd source the translations and avoid using a gem.

I think this guide http://guides.rubyonrails.org/i18n.html should give us a good starting place.

**Comment by fabriciojr** [comment]
@tarebyte I think you misunderstood it, I wasn't thinking about using a gem, there's no good reason for it. My concern was about any text coming from external gems or JS libraries. Did you get it?

**Comment by tarebyte** [comment]
@fabriciojr oh I understand what you're saying. There is only once place where external next would come from and that is the repository auto completer.

For the most part we wrap the errors ourselves from the GitHub API.

**Comment by fabriciojr** [comment]
@tarebyte Thanks for the two cents. I'll keep working on it. Can you assign it to me?

**Comment by tarebyte** [comment]
@fabriciojr unfortunately I can't because you aren't apart of the Education organization nor are you an outside collaborator. Sorry about that.

**Comment by fabriciojr** [comment]
@tarebyte No problem, I'm going to start coding here. 😄

**Comment by CGA1123** [comment]
Is there any work being done on this?

I'd be happy to start picking off some of these objectives.

**Comment by jiteshjha** [comment]
Hi! I've worked on I18n in Google Summer of Code this year and I would love to help in the internationalization process! :smile:

**Comment by tarebyte** [comment]
@jiteshjha feel free! Pull Requests are always welcomed 😄

**Comment by CGA1123** [comment]
What file structure should be used for holding the translation strings?

```
|-views
|---shared
|-----en.yml
|---pages
|-----en.yml
```
(similar structure as mentioned [here](http://guides.rubyonrails.org/i18n.html#organization-of-locale-files))
Does something along those lines look reasonable?

Sticking with a single `en.yml` in `config/locales` doesn't seem like the best approach.

**Comment by tarebyte** [comment]
@CGA1123 I want to stick to the Rails convention to reduce the overhead of other people who work on this later.

Reference: http://guides.rubyonrails.org/i18n.html

**Comment by nwoodthorpe** [comment]
Shoo probot
