### ISSUE TITLE
Assignment Submission Flow

### ISSUE THREAD

**Issue by cyhsutw** [education/classroom#667]
Hi everyone,

We're going to add a feature that students can choose a specific version of their works to submit for grading (a part of #572).

_This is a potential implementation, would love to hear your feedback/suggestions on this!_ 😄 
### Usage flows
- For **students**, the submission is really simple: create a _Release_ on GitHub.com for the version she/he would like the teacher to grade.
- For **teachers**, Classroom will aggregate the latest submissions so teachers can grade.
### Roadmap

Backend:
- [x] Create migrations and update models to support organization webhooks and due dates for assignments
- [ ] Add functionalities to set webhook for organization and create a controller to handle `ping` event
- [ ] Add functionalities to create commit statuses for `push` events and `release` events

Frontend:
- [ ] Add functionality to let teachers specify due date of assignments
- [ ] Add functionality to let organization admins to set webhook if there isn't one
- [ ] Expose submission statuses (on time/overdue) to students

Edit: 
As @jayvdb mentioned in [#720 (comment)](https://github.com/education/classroom/pull/720#issuecomment-249790724), we should also keep a list of submitted SHAs (along with the timestamp of the submission) so the grading process for teachers can be more flexible and reasonable.

**Comment by nwoodthorpe** [comment]
I'd love to see this happen, but it's fallen inactive. If we decide we want to implement this, we'll re-open.
